# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentos.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agentos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ragentos.proto\x12\x07\x61gentos\"Y\n\x0fRegisterRequest\x12\x0b\n\x03\x64id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x02 \x03(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\x11\n\tsignature\x18\x04 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x0f\x44iscoverRequest\x12\x12\n\ncapability\x18\x01 \x01(\t\"D\n\rAgentMetadata\x12\x0b\n\x03\x64id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x02 \x03(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\":\n\x10\x44iscoverResponse\x12&\n\x06\x61gents\x18\x01 \x03(\x0b\x32\x16.agentos.AgentMetadata\"\x96\x01\n\x0bTaskRequest\x12\x11\n\tbuyer_did\x18\x01 \x01(\t\x12\x12\n\ntarget_did\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x11\n\tmax_price\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x16\n\x0epayload_string\x18\x06 \x01(\t\x12\x11\n\tsignature\x18\x07 \x01(\t\"c\n\x0cTaskResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x15\n\rsettled_price\x18\x03 \x01(\x01\x12\x14\n\x0c\x61i_reasoning\x18\x04 \x01(\t\"\\\n\tDataChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x03\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x11\n\tsignature\x18\x04 \x01(\t\"f\n\x11\x44\x61taChunkResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x03\x12\x14\n\x0c\x61\x63knowledged\x18\x03 \x01(\x08\x12\x0e\n\x06status\x18\x04 \x01(\t2\x9c\x01\n\rAgentRegistry\x12\x44\n\rRegisterAgent\x12\x18.agentos.RegisterRequest\x1a\x19.agentos.RegisterResponse\x12\x45\n\x0e\x44iscoverAgents\x12\x18.agentos.DiscoverRequest\x1a\x19.agentos.DiscoverResponse2\x8d\x01\n\tAgentNode\x12:\n\x0b\x45xecuteTask\x12\x14.agentos.TaskRequest\x1a\x15.agentos.TaskResponse\x12\x44\n\x0eStreamTaskData\x12\x12.agentos.DataChunk\x1a\x1a.agentos.DataChunkResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=26
  _globals['_REGISTERREQUEST']._serialized_end=115
  _globals['_REGISTERRESPONSE']._serialized_start=117
  _globals['_REGISTERRESPONSE']._serialized_end=169
  _globals['_DISCOVERREQUEST']._serialized_start=171
  _globals['_DISCOVERREQUEST']._serialized_end=208
  _globals['_AGENTMETADATA']._serialized_start=210
  _globals['_AGENTMETADATA']._serialized_end=278
  _globals['_DISCOVERRESPONSE']._serialized_start=280
  _globals['_DISCOVERRESPONSE']._serialized_end=338
  _globals['_TASKREQUEST']._serialized_start=341
  _globals['_TASKREQUEST']._serialized_end=491
  _globals['_TASKRESPONSE']._serialized_start=493
  _globals['_TASKRESPONSE']._serialized_end=592
  _globals['_DATACHUNK']._serialized_start=594
  _globals['_DATACHUNK']._serialized_end=686
  _globals['_DATACHUNKRESPONSE']._serialized_start=688
  _globals['_DATACHUNKRESPONSE']._serialized_end=790
  _globals['_AGENTREGISTRY']._serialized_start=793
  _globals['_AGENTREGISTRY']._serialized_end=949
  _globals['_AGENTNODE']._serialized_start=952
  _globals['_AGENTNODE']._serialized_end=1093
# @@protoc_insertion_point(module_scope)
