# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agentos_pb2 as agentos__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agentos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentRegistryStub:
    """Discovery Service definition for Agent Registry
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/agentos.AgentRegistry/RegisterAgent',
                request_serializer=agentos__pb2.RegisterRequest.SerializeToString,
                response_deserializer=agentos__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.DiscoverAgents = channel.unary_unary(
                '/agentos.AgentRegistry/DiscoverAgents',
                request_serializer=agentos__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=agentos__pb2.DiscoverResponse.FromString,
                _registered_method=True)


class AgentRegistryServicer:
    """Discovery Service definition for Agent Registry
    """

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=agentos__pb2.RegisterRequest.FromString,
                    response_serializer=agentos__pb2.RegisterResponse.SerializeToString,
            ),
            'DiscoverAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverAgents,
                    request_deserializer=agentos__pb2.DiscoverRequest.FromString,
                    response_serializer=agentos__pb2.DiscoverResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.AgentRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentos.AgentRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRegistry:
    """Discovery Service definition for Agent Registry
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.AgentRegistry/RegisterAgent',
            agentos__pb2.RegisterRequest.SerializeToString,
            agentos__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.AgentRegistry/DiscoverAgents',
            agentos__pb2.DiscoverRequest.SerializeToString,
            agentos__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentNodeStub:
    """Peer-to-Peer Service definition for direct agent handshakes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/agentos.AgentNode/ExecuteTask',
                request_serializer=agentos__pb2.TaskRequest.SerializeToString,
                response_deserializer=agentos__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.StreamTaskData = channel.stream_stream(
                '/agentos.AgentNode/StreamTaskData',
                request_serializer=agentos__pb2.DataChunk.SerializeToString,
                response_deserializer=agentos__pb2.DataChunkResponse.FromString,
                _registered_method=True)


class AgentNodeServicer:
    """Peer-to-Peer Service definition for direct agent handshakes
    """

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTaskData(self, request_iterator, context):
        """Bidirectional Streaming RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=agentos__pb2.TaskRequest.FromString,
                    response_serializer=agentos__pb2.TaskResponse.SerializeToString,
            ),
            'StreamTaskData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTaskData,
                    request_deserializer=agentos__pb2.DataChunk.FromString,
                    response_serializer=agentos__pb2.DataChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.AgentNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentos.AgentNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentNode:
    """Peer-to-Peer Service definition for direct agent handshakes
    """

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.AgentNode/ExecuteTask',
            agentos__pb2.TaskRequest.SerializeToString,
            agentos__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTaskData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/agentos.AgentNode/StreamTaskData',
            agentos__pb2.DataChunk.SerializeToString,
            agentos__pb2.DataChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
